### ISSUE TITLE
Start slider at 1960 for thermoelectric

### ISSUE THREAD

**Issue by wdwatkins** [USGS-VIZLAB/water-use#132]
A logical thing to do when you first open the viz is switch to thermoelectric since its the next category, but you immediately get a full no-data map:
![image](https://cloud.githubusercontent.com/assets/13987349/20897691/0436d504-bae9-11e6-83b0-47717d501cb1.png)
I could see someone just thinking it is broken and leaving.  I think user experience would be much improved if the slider moves to 1960 (if it is at 1950 or 55), with a box in the lower left maybe that explains that the cateogory didn't exist then).

**Comment by dblodgett-usgs** [comment]
We could just start at 1960 period. The 1950/55 data is problematic.

**Comment by eread-usgs** [comment]
what happens when you switch back from thermo to another category? does it go back to 1950? Issue #121 could also help with this and could be an alternative.

**Comment by wdwatkins** [comment]
I would say it could switch back to 1950/55, **if** that is where the slider was in the last category.  Or maybe just if the slider hasn't been moved yet at all.

**Comment by eread-usgs** [comment]
I think we should keep the default as either 1950 or 2010, and not have it change for different categories. I also think someone would try clicking another category before just assuming the thing is broken and leaving the site. I think between #121 and making the default 2010, we should be good (unless we hear otherwise from reviewers). I'm going to close this issue and note the default date elsewhere.

**Comment by wdwatkins** [comment]
Default to 2010 would solve this and is definitely easier.  I think the box noting that the category wasn't used those years would be worth having though as a lower-priority issue
