### ISSUE TITLE
map scaling and translation

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/water-use#30]
make it so its easy to take scale transform and keep the centroid location constant.

**Comment by jordansread** [comment]
This https://css-tricks.com/transforms-on-svg-elements/ explains why this is challenging. 

my approach is to center each polygon element at `0,0` for its coordinates, then `transform = translate(x,y)` its parent group to get it in place. Then apply the CSS scale to the element itself (based on 0,0 native) as a scale only, cutting out the need to keep up with the scale and transform that would otherwise need to happen simultaneously whenever an element is scaled. 

need to see if this will work first.

**Comment by jordansread** [comment]
Ok, looks like I can do that thing ☝️ 

if the geom is written to center in the upper left corner of the svg (the 0,0 in svg space), and then I group that geom and use a translate on the group to get it in the right place, I can scale the actual geom w/o having to do an x/y translate at the same time. Looks kind of like this:

```xml
<g id='texas-g' transform='translate(300,200)'>
  <path d='M 129.01 8.90 L 129.35 9.14 L 129.48 9.65 L 129.72 ... id='texas'
</g>
```
![image](https://cloud.githubusercontent.com/assets/2349007/20837041/d77b5f22-b867-11e6-9d3f-0da3dfa0e059.png)

then 
```js
document.getElementById('texas-polygon').setAttribute('transform','scale(0.2)')
```

creates 
![image](https://cloud.githubusercontent.com/assets/2349007/20837067/f50bd896-b867-11e6-9fed-fa533e0bec3a.png)

which remains in the right place (these are quick screen snips, so it doesn't look right, but it is)

**Comment by jordansread** [comment]
The challenge is getting the actual svg to be written with the shifted geom in the real 0,0

I use the bbox of all of the states in their proper places to define the plot, but `sp::plot()` is going to honor whichever dim matters to keep the aspect ratio of the plot right, so I need to figure that out. I think this can be done by defining the output size first, and using that rectangle to define xlim and ylim so both are correct and can be used to shift the centroids to 0,0

Right now the 0,0 shift is off, because of what I mentioned above:
![image](https://cloud.githubusercontent.com/assets/2349007/20837218/b4f50e8e-b868-11e6-8086-f586ae4aeccb.png)

where the red dot is the 0,0 of the svg canvas

**Comment by jordansread** [comment]
Can animate the scaling with css easily:

```css
.texas-scaled {
	  transform: scale(0.3);
	  fill: blue;
	  transition: all .2s ease-in-out; 
	}
```
or we could do it w/ a delay loop in js, where we interpolate the starting point for the scale (what it is now) to the ending point.

**Comment by jordansread** [comment]
@jiwalker-usgs is working on the preferred way to do the changes I think?

**Comment by jordansread** [comment]
When I write the svg canvas size to be the same scale as the canvas that I expect to plot, the actual centroid and the 0,0 reference centroid are still off:

![image](https://cloud.githubusercontent.com/assets/2349007/20837973/0db8f6d6-b86c-11e6-8285-1b2b0fd96c72.png)

:(

maybe a par setting that I am missing, or something sp::plot is doing that I don't quite understand.

**Comment by jordansread** [comment]
YAY!
`setParUsrBB = TRUE` is what allows me to lock the dims to expected
![image](https://cloud.githubusercontent.com/assets/2349007/20838107/bcc555ac-b86c-11e6-8d4d-e32b384e8d3b.png)

**Comment by dblodgett-usgs** [comment]
🎯

**Comment by jordansread** [comment]
Centroids!~

![image](https://cloud.githubusercontent.com/assets/2349007/20838957/5b5a7dfc-b870-11e6-8b11-d301e260b144.png)

**Comment by jiwalker-usgs** [comment]
Yeah, we will create that CSS rule (above) and apply it to each state.  Hopefully this will be nice and smooth.  One tip I found is to perhaps use `scale3d` to gain the benefit of the GPU on most modern browsers.

**Comment by jordansread** [comment]
done
